const KEY='gabineteDigitalDemo';
let db=JSON.parse(localStorage.getItem(KEY)||'{"people":[],"agenda":[]}');
db.people=Array.isArray(db.people)?db.people:[];db.agenda=Array.isArray(db.agenda)?db.agenda:[];
let editandoId=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(db));render();renderDemandas();renderAgenda();renderBirthdays();atualizarPainel()}
function mostrarAba(nome){document.querySelectorAll('.tab').forEach(a=>a.style.display='none');const a=document.getElementById(nome);if(a)a.style.display='block';if(nome==='pessoas')render();if(nome==='demandas')renderDemandas();if(nome==='agenda')renderAgenda();if(nome==='aniversarios')renderBirthdays();if(nome==='painel')atualizarPainel();window.scrollTo({top:0,behavior:'smooth'})}window.mostrarAba=mostrarAba;
function wa(t,m){let n=String(t||'').replace(/\D/g,'');if(!n){alert('Telefone não cadastrado.');return}if(n.length===10||n.length===11)n='55'+n;window.open('https://wa.me/'+n+'?text='+encodeURIComponent(m),'_blank')}window.wa=wa;
function birth(p){const v=String(p.nascimento||'').trim();if(!v)return null;let d,mo,y,x=v.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);if(x){d=+x[1];mo=+x[2];y=+x[3]}if(!x){x=v.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(x){y=+x[1];mo=+x[2];d=+x[3]}}if(!d||!mo||!y)return null;const now=new Date();let date=new Date(now.getFullYear(),mo-1,d);const today=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(date<today)date.setFullYear(date.getFullYear()+1);return date}
const formCadastro=$('#formCadastro');
if(formCadastro)formCadastro.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.demanda=d.demanda||'';d.tipoDemanda=d.tipoDemanda||'';d.tipo=d.tipoDemanda||'';d.status=d.status||'Pendente';if(editandoId){const i=db.people.findIndex(p=>p.id===editandoId);if(i!==-1)db.people[i]={...db.people[i],...d,id:editandoId};editandoId=null;alert('Cadastro atualizado com sucesso!')}else{d.id=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString();d.criadoEm=new Date().toISOString();db.people.unshift(d);alert('Cadastro salvo com sucesso!')}e.target.reset();const b=formCadastro.querySelector('button[type="submit"]');if(b)b.textContent='Salvar cadastro';save();mostrarAba('pessoas')});
window.editarCadastro=id=>{const p=db.people.find(x=>x.id===id);if(!p||!formCadastro)return alert('Cadastro não encontrado.');editandoId=id;Object.keys(p).forEach(k=>{const el=formCadastro.elements[k];if(el&&k!=='id'&&k!=='criadoEm')el.value=p[k]||''});if(formCadastro.elements.tipoDemanda)formCadastro.elements.tipoDemanda.value=p.tipoDemanda||p.tipo||'';const b=formCadastro.querySelector('button[type="submit"]');if(b)b.textContent='Atualizar cadastro';mostrarAba('cadastro')};
window.cancelarEdicao=()=>{editandoId=null;formCadastro?.reset();const b=formCadastro?.querySelector('button[type="submit"]');if(b)b.textContent='Salvar cadastro'};
window.excluirCadastro=id=>{const p=db.people.find(x=>x.id===id);if(!p)return alert('Cadastro não encontrado.');if(!confirm(`Deseja realmente excluir o cadastro de ${p.nome||'esta pessoa'}?\n\nEssa ação não pode ser desfeita.`))return;db.people=db.people.filter(x=>x.id!==id);save();alert('Cadastro excluído com sucesso!')};
window.verCadastro=id=>{const p=db.people.find(x=>x.id===id);if(!p)return alert('Cadastro não encontrado.');alert([`NOME: ${p.nome||'Não informado'}`,`MÃE: ${p.mae||'Não informado'}`,`NASCIMENTO: ${p.nascimento||'Não informado'}`,`CPF: ${p.cpf||'Não informado'}`,`SUS: ${p.sus||'Não informado'}`,`TELEFONE: ${p.telefone||'Não informado'}`,`BAIRRO: ${p.bairro||'Não informado'}`,`ENDEREÇO: ${p.endereco||'Não informado'}`,`DEMANDA: ${p.demanda||'Não informada'}`,`TIPO DE DEMANDA: ${p.tipoDemanda||p.tipo||'Não informado'}`,`PROCEDIMENTO / SERVIÇO: ${p.procedimento||'Não informado'}`,`STATUS: ${p.status||'Pendente'}`].join('\n'))};
function statusClass(s){return s==='Concluído'?'concluido':s==='Em andamento'?'andamento':'pendente'}
function mudarStatus(id,status){const p=db.people.find(x=>x.id===id);if(!p)return;p.status=status;save()}window.mudarStatus=mudarStatus;
function render(){const busca=($('#buscaPessoa')?.value||'').toLowerCase().trim(),bairro=($('#filtroBairro')?.value||'').toLowerCase().trim(),c=$('#listaPessoas');if(!c)return;const pessoas=db.people.filter(p=>{const texto=[p.nome,p.mae,p.cpf,p.sus,p.telefone,p.bairro,p.endereco,p.demanda,p.tipoDemanda,p.tipo,p.procedimento,p.status].join(' ').toLowerCase();return(!busca||texto.includes(busca))&&(!bairro||String(p.bairro||'').toLowerCase().includes(bairro))});c.innerHTML=pessoas.map(p=>{const st=p.status||'Pendente';return `<div class="card"><h3>${esc(p.nome)}</h3><p>${esc(p.bairro||'Bairro não informado')} • ${esc(p.telefone||'Telefone não informado')}</p><p><strong>Demanda:</strong> ${esc(p.demanda||'Não informada')}</p><p><strong>Tipo:</strong> ${esc(p.tipoDemanda||p.tipo||'Não informado')}</p>${p.procedimento?`<p><strong>Procedimento:</strong> ${esc(p.procedimento)}</p>`:''}<span class="status ${statusClass(st)}">${esc(st)}</span><div class="acoes"><button type="button" onclick="mudarStatus('${esc(p.id)}','Pendente')">Pendente</button><button type="button" onclick="mudarStatus('${esc(p.id)}','Em andamento')">Em andamento</button><button type="button" onclick="mudarStatus('${esc(p.id)}','Concluído')">Concluído</button></div><div class="acoes"><button type="button" onclick="verCadastro('${esc(p.id)}')">Ver cadastro</button><button type="button" onclick="editarCadastro('${esc(p.id)}')">Editar</button><button type="button" onclick="excluirCadastro('${esc(p.id)}')">Excluir</button>${p.telefone?`<button type="button" onclick="wa('${esc(p.telefone)}','Olá, ${esc(p.nome)}!')">WhatsApp</button>`:''}</div></div>`}).join('')||'<div class="card vazio"><h3>Nenhum cadastro encontrado</h3><p>Tente outro termo de busca ou faça um novo cadastro.</p></div>';atualizarPainel()}
function atualizarPainel(){const c=$('#painelConteudo');if(!c)return;const total=db.people.length,pend=db.people.filter(p=>(p.status||'Pendente')==='Pendente').length,and=db.people.filter(p=>p.status==='Em andamento').length,conc=db.people.filter(p=>p.status==='Concluído').length;const hoje=new Date().toISOString().slice(0,10),agendaHoje=db.agenda.filter(a=>a.data===hoje).length,aniversHoje=getBirthdays().filter(x=>x.date.getMonth()===new Date().getMonth()&&x.date.getDate()===new Date().getDate()).length;c.innerHTML=`<div class="card"><p>PESSOAS</p><div class="numero">${total}</div><p>cadastradas</p></div><div class="card"><p>PENDENTES</p><div class="numero">${pend}</div><p>aguardando atendimento</p></div><div class="card"><p>EM ANDAMENTO</p><div class="numero">${and}</div><p>demandas acompanhadas</p></div><div class="card"><p>CONCLUÍDAS</p><div class="numero">${conc}</div><p>demandas resolvidas</p></div><div class="card"><p>AGENDA HOJE</p><div class="numero">${agendaHoje}</div><p>compromisso(s)</p></div><div class="card"><p>ANIVERSÁRIOS HOJE</p><div class="numero">${aniversHoje}</div><p>cidadão(s)</p></div>`}
function renderDemandas(){const c=$('#listaDemandas');if(!c)return;const d=db.people.filter(p=>p.demanda);c.innerHTML=d.map(p=>{const st=p.status||'Pendente';return `<div class="card"><h3>${esc(p.demanda)}</h3><p><strong>Pessoa:</strong> ${esc(p.nome)}</p><p><strong>Tipo:</strong> ${esc(p.tipoDemanda||p.tipo||'Não informado')}</p><p><strong>Bairro:</strong> ${esc(p.bairro||'Não informado')}</p>${p.procedimento?`<p><strong>Procedimento:</strong> ${esc(p.procedimento)}</p>`:''}<span class="status ${statusClass(st)}">${esc(st)}</span><div class="acoes"><button type="button" onclick="mudarStatus('${esc(p.id)}','Pendente')">Pendente</button><button type="button" onclick="mudarStatus('${esc(p.id)}','Em andamento')">Em andamento</button><button type="button" onclick="mudarStatus('${esc(p.id)}','Concluído')">Concluído</button></div><div class="acoes"><button type="button" onclick="editarCadastro('${esc(p.id)}')">Editar</button>${p.telefone?`<button type="button" onclick="wa('${esc(p.telefone)}','Olá, ${esc(p.nome)}! Estou entrando em contato sobre sua demanda: ${esc(p.demanda)}.')">WhatsApp</button>`:''}</div></div>`}).join('')||'<div class="card vazio"><h3>Nenhuma demanda cadastrada</h3><p>As demandas aparecem aqui automaticamente quando um cidadão é cadastrado.</p></div>'}
const formAgenda=$('#formAgenda');if(formAgenda)formAgenda.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString();db.agenda.push(d);e.target.reset();save();alert('Compromisso adicionado à agenda!')});window.excluirAgenda=id=>{if(confirm('Excluir este compromisso da agenda?')){db.agenda=db.agenda.filter(x=>x.id!==id);save()}};
function renderAgenda(){const c=$('#listaAgenda');if(!c)return;const a=[...db.agenda].sort((x,y)=>(String(x.data||'')+String(x.hora||'')).localeCompare(String(y.data||'')+String(y.hora||'')));c.innerHTML=a.map(i=>`<div class="card"><h3>${esc(i.assunto||'Compromisso')}</h3><p>📅 ${i.data?new Date(i.data+'T00:00:00').toLocaleDateString('pt-BR'):'Sem data'}${i.hora?' • ⏰ '+esc(i.hora):''}</p>${i.tipo?`<p><strong>Tipo:</strong> ${esc(i.tipo)}</p>`:''}<p><strong>Status:</strong> ${esc(i.status||'Pendente')}</p><div class="acoes"><button type="button" onclick="excluirAgenda('${esc(i.id)}')">Excluir</button></div></div>`).join('')||'<div class="card vazio"><h3>Agenda vazia</h3><p>Adicione reuniões, atendimentos, eventos e visitas acima.</p></div>'}
function getBirthdays(){return db.people.map(p=>({person:p,date:birth(p)})).filter(x=>x.date).sort((a,b)=>a.date-b.date)}function renderBirthdays(){const c=$('#listaAniversarios');if(!c)return;const b=getBirthdays();c.innerHTML=b.map(x=>`<div class="card"><h3>🎂 ${esc(x.person.nome)}</h3><p>Aniversário: ${x.date.toLocaleDateString('pt-BR')}</p>${x.person.telefone?`<button type="button" onclick="wa('${esc(x.person.telefone)}','Parabéns, ${esc(x.person.nome)}! 🎉 Desejamos muita saúde, felicidade e um excelente novo ciclo!')">Enviar felicitações pelo WhatsApp</button>`:''}</div>`).join('')||'<div class="card vazio"><h3>Nenhum aniversário cadastrado</h3><p>Cadastre a data de nascimento dos cidadãos para aparecerem aqui.</p></div>'}
$('#buscaPessoa')?.addEventListener('input',render);$('#filtroBairro')?.addEventListener('input',render);window.imprimirPessoas=()=>window.print();document.addEventListener('DOMContentLoaded',()=>{render();renderDemandas();renderAgenda();renderBirthdays();atualizarPainel();mostrarAba('painel')});window.render=render;window.renderDemandas=renderDemandas;window.renderAgenda=renderAgenda;window.renderBirthdays=renderBirthdays;window.getBirthdays=getBirthdays;
