/* Gabinete LM — Auditoria administrativa */
(function(){'use strict';
const CFG='gabineteSupabaseConfig',AT='gabineteAccessToken';
const cfg=()=>{try{return JSON.parse(localStorage.getItem(CFG)||'{}')}catch(e){return{}}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const token=()=>localStorage.getItem(AT)||'';
function style(){if(document.getElementById('auditoriaStyle'))return;const s=document.createElement('style');s.id='auditoriaStyle';s.textContent='.aud-modal{position:fixed;inset:0;background:#0f172acc;z-index:2147483646;display:flex;align-items:center;justify-content:center;padding:16px;font-family:Arial}.aud-box{background:#fff;width:min(1050px,100%);max-height:90vh;overflow:auto;border-radius:18px;padding:20px;box-shadow:0 20px 60px #0005}.aud-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.aud-filt{display:grid;grid-template-columns:1fr 180px 180px auto;gap:8px;margin:14px 0}.aud-filt input,.aud-filt select{padding:10px;border:1px solid #dbe1ea;border-radius:9px}.aud-table{width:100%;border-collapse:collapse;font-size:13px}.aud-table th,.aud-table td{padding:9px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}.aud-pill{display:inline-block;padding:3px 7px;border-radius:99px;background:#eef2ff}.aud-close{border:0;border-radius:9px;padding:9px 12px;cursor:pointer}.aud-empty{padding:28px;text-align:center;color:#64748b}@media(max-width:700px){.aud-filt{grid-template-columns:1fr 1fr}.aud-table{font-size:12px}.aud-table th:nth-child(4),.aud-table td:nth-child(4){display:none}}';document.head.appendChild(s)}
async function req(path){const c=cfg();if(!c.url||!c.anonKey)throw Error('Supabase não configurado.');const r=await fetch(String(c.url).replace(/\/+$/,'')+path,{headers:{apikey:c.anonKey,Authorization:'Bearer '+token()}});const j=await r.json().catch(()=>[]);if(!r.ok)throw Error(j.message||j.error||'Não foi possível carregar a auditoria.');return j}
const label={INSERT:'Criação',UPDATE:'Alteração',DELETE:'Exclusão'};function fmt(v){if(!v)return '—';try{return new Date(v).toLocaleString('pt-BR')}catch(e){return v}}function resumo(d){if(!d)return '—';const x=d.depois||d.antes||d;return String(x.nome||x.assunto||x.descricao||x.id||'Registro atualizado')}
async function open(){if(document.getElementById('auditoriaModal'))return;style();const m=document.createElement('div');m.id='auditoriaModal';m.className='aud-modal';m.innerHTML='<div class="aud-box"><div class="aud-head"><div><span style="color:#4f46e5;font-weight:700">CONTROLE</span><h2 style="margin:4px 0">Auditoria do gabinete</h2><small style="color:#64748b">Registro de alterações realizadas no sistema.</small></div><button class="aud-close">✕ Fechar</button></div><div class="aud-filt"><input id="audBusca" placeholder="🔎 Buscar registro, usuário ou ID"><select id="audTabela"><option value="">Todas as áreas</option><option value="cidadaos">Cidadãos</option><option value="demandas">Demandas</option><option value="agenda">Agenda</option><option value="atendimentos">Atendimentos</option></select><select id="audAcao"><option value="">Todas as ações</option><option value="INSERT">Criações</option><option value="UPDATE">Alterações</option><option value="DELETE">Exclusões</option></select><button id="audAtualizar">Atualizar</button></div><div id="audLista"><div class="aud-empty">Carregando…</div></div></div>';document.body.appendChild(m);m.querySelector('.aud-close').onclick=()=>m.remove();['audBusca','audTabela','audAcao'].forEach(id=>m.querySelector('#'+id).addEventListener('input',render));m.querySelector('#audAtualizar').onclick=load;await load()}
let rows=[];async function load(){const b=document.getElementById('audLista');if(!b)return;b.innerHTML='<div class="aud-empty">Carregando auditoria…</div>';try{rows=await req('/rest/v1/auditoria_gabinete?select=*&order=criado_em.desc&limit=200');render()}catch(e){b.innerHTML='<div class="aud-empty">⚠️ '+esc(e.message)+'</div>'}}
function render(){const b=document.getElementById('audLista');if(!b)return;const q=(document.getElementById('audBusca')?.value||'').toLowerCase(),t=document.getElementById('audTabela')?.value||'',a=document.getElementById('audAcao')?.value||'';const r=rows.filter(x=>(!t||x.tabela===t)&&(!a||x.acao===a)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));if(!r.length){b.innerHTML='<div class="aud-empty">Nenhum registro encontrado.</div>';return}b.innerHTML='<table class="aud-table"><thead><tr><th>Data / hora</th><th>Área</th><th>Ação</th><th>Registro</th><th>Usuário</th><th>Resumo</th></tr></thead><tbody>'+r.map(x=>'<tr><td>'+esc(fmt(x.criado_em))+'</td><td>'+esc(x.tabela)+'</td><td><span class="aud-pill">'+esc(label[x.acao]||x.acao)+'</span></td><td>'+esc(x.registro_id||'—')+'</td><td>'+esc(x.usuario_id||'—')+'</td><td>'+esc(resumo(x.detalhes))+'</td></tr>').join('')+'</tbody></table>'}
window.abrirAuditoriaGabinete=open;
const sc=document.createElement('script');sc.src='destino-demanda-v1.js?v=1001';document.head.appendChild(sc);
})();