/* GABINETE DIGITAL — BANCO CENTRAL v14
   Offline-first: baixa, mescla por data de atualização, envia e confirma.
   Mantém dados locais quando estiver sem internet ou sem sessão.
*/
(function(){'use strict';
const DB='gabineteDigitalDemo',CFG='gabineteSupabaseConfig',SES='gabineteSupabaseSession',AT='gabineteAccessToken',LOCK='__gabinete_v14_syncing__';
const get=Storage.prototype.getItem,set=Storage.prototype.setItem,remove=Storage.prototype.removeItem;
const states=['Pará','Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Paraná','Paraíba','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins'];
const isState=v=>states.some(s=>s.toLowerCase()===String(v||'').trim().toLowerCase());
const norm=v=>String(v??'').trim().replace(/\s+/g,' ');
const read=()=>{try{const d=JSON.parse(get.call(localStorage,DB)||'{"people":[],"agenda":[]}');d.people=Array.isArray(d.people)?d.people:[];d.agenda=Array.isArray(d.agenda)?d.agenda:[];return d}catch(e){return{people:[],agenda:[]}}};
const write=d=>{window.__gabineteCentralWriting=true;try{set.call(localStorage,DB,JSON.stringify(d))}finally{setTimeout(()=>{window.__gabineteCentralWriting=false},0)}};
const cfg=()=>{try{return JSON.parse(get.call(localStorage,CFG)||'null')}catch(e){return null}};
const session=()=>{try{return JSON.parse(get.call(localStorage,SES)||'null')}catch(e){return null}};
const token=()=>get.call(localStorage,AT)||session()?.access_token||'';
const base=()=>{const c=cfg();return c?.url?String(c.url).replace(/\/+$/,''):''};
const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const valid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const date=v=>{const s=norm(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);return m?m[3]+'-'+m[2]+'-'+m[1]:null};
const iso=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?t:0};
function limparOrigem(v){let s=norm(v);if(!s)return{city:'',state:''};const parts=s.split(/\s*(?:\/|-|—|,)\s*/).filter(Boolean);let state='',cityParts=[];parts.forEach(part=>{const st=states.find(x=>x.toLowerCase()===part.toLowerCase());if(st)state=st;else cityParts.push(part)});if(state)return{city:norm(cityParts.join(' / ')),state};if(isState(s))return{city:'',state:states.find(x=>x.toLowerCase()===s.toLowerCase())||s};return{city:s,state:''}}
function origemCampos(p){let city=norm(p?.cidadeNascimento||p?.cidadeOrigem),state=norm(p?.estadoNascimento||p?.estadoOrigem);if(isState(city)){if(!state)state=city;city=''}if(!state){const s=norm(p?.origemNascimento),x=limparOrigem(s);if(x.state){if(!city)city=x.city;state=x.state}else if(!city)city=x.city}if(isState(city)){if(!state)state=city;city=''}return{city,state}}
function normal(p){if(!valid(p.id))p.id=uuid();if(!p.atualizadoEm)p.atualizadoEm=p.criadoEm||new Date().toISOString();if(!Array.isArray(p.demandas))p.demandas=[];p.demandas=p.demandas.map(d=>{if(!valid(d.id))d.id=uuid();if(!d.atualizadoEm)d.atualizadoEm=d.criadoEm||p.atualizadoEm;d.status=['Pendente','Em andamento','Concluído'].includes(d.status)?d.status:'Pendente';return d});return p}
function newer(a,b){return iso(a?.atualizadoEm||a?.criadoEm)>=iso(b?.atualizadoEm||b?.criadoEm)}
function mergePeople(local,remote){const rm=new Map((remote||[]).map(p=>[String(p.id),normal(p)])),out=[];for(const raw of(local||[])){const l=normal(raw),q=rm.get(String(l.id));if(!q){out.push(l);continue}const winner=newer(l,q)?l:q,loser=winner===l?q:l,lc=origemCampos(winner),rc=origemCampos(loser),city=lc.city||rc.city,state=lc.state||rc.state,merged=Object.assign({},loser,winner);merged.cidadeNascimento=city;merged.estadoNascimento=state;merged.cidadeOrigem=city;merged.estadoOrigem=state;merged.origemNascimento=city&&state?city+' / '+state:city||state||'';const dm=new Map((q.demandas||[]).map(d=>[String(d.id),d]));(l.demandas||[]).forEach(d=>{const r=dm.get(String(d.id));dm.set(String(d.id),r&&iso(r.atualizadoEm)>iso(d.atualizadoEm)?r:d)});merged.demandas=[...dm.values()];out.push(merged);rm.delete(String(l.id))}for(const p of rm.values())out.push(p);return out}
function mergeAgenda(local,remote){const rm=new Map((remote||[]).map(a=>[String(a.id),a])),out=[];(local||[]).forEach(raw=>{const l=Object.assign({},raw);if(!valid(l.id))l.id=uuid();const r=rm.get(String(l.id));if(!r){out.push(l);return}out.push(newer(l,r)?l:r);rm.delete(String(l.id))});for(const a of rm.values())out.push(a);return out}
async function refreshSession(){const c=cfg(),s=session(),rt=s?.refresh_token;if(!c?.url||!c?.anonKey||!rt)return false;try{const res=await fetch(base()+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt}),cache:'no-store'});if(!res.ok)return false;const j=await res.json();if(!j?.access_token)return false;const ns=Object.assign({},s,j);set.call(localStorage,SES,JSON.stringify(ns));set.call(localStorage,AT,j.access_token);return true}catch(e){return false}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function req(path,opt={},again=true,retries=2){const c=cfg();if(!c?.url||!c?.anonKey)throw Error('Supabase não configurado');let t=token();if(!t){await refreshSession();t=token()}if(!t)throw Error('Sessão não disponível neste aparelho');const h=Object.assign({apikey:c.anonKey,'Content-Type':'application/json',Authorization:'Bearer '+t},opt.headers||{});let res;try{res=await fetch(base()+path,Object.assign({},opt,{headers:h,cache:'no-store'}))}catch(e){if(retries>0){await sleep(700);return req(path,opt,again,retries-1)}throw Error('Sem conexão com o Supabase')}if(res.status===401&&again&&await refreshSession())return req(path,opt,false,retries);if(!res.ok){const txt=await res.text();if([408,425,429,500,502,503,504].includes(res.status)&&retries>0){await sleep(900);return req(path,opt,again,retries-1)}throw Error('HTTP '+res.status+' '+txt)}const txt=await res.text();return txt?JSON.parse(txt):null}
async function upsert(table,rows){if(rows.length)await req('/rest/v1/'+table+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
function personRow(p){return{id:p.id,nome:p.nome||'',nome_mae:p.mae||null,data_nascimento:date(p.nascimento),cpf:p.cpf||null,cartao_sus:p.sus||null,telefone:p.telefone||null,bairro:p.bairro||null,endereco:p.endereco||null,cep:p.cep||null,cidade_origem:(()=>{const x=origemCampos(p);return x.city&&x.state?x.city+' / '+x.state:x.city||x.state||null})(),nacionalidade:p.nacionalidade||null,raca_cor:p.racaCor||null,observacoes:p.observacoes||null,apelido:p.apelido||null,ponto_referencia:p.pontoReferencia||null,criado_em:p.criadoEm||p.atualizadoEm||new Date().toISOString(),atualizado_em:p.atualizadoEm||p.criadoEm||new Date().toISOString()}}
function demandList(p){let ds=Array.isArray(p.demandas)?p.demandas.slice():[];if(!ds.length&&p.demanda)ds=[{id:p.demandaId||uuid(),demanda:p.demanda,tipoDemanda:p.tipoDemanda||p.tipo||'Outro',tipo:p.tipoDemanda||p.tipo||'Outro',procedimento:p.procedimento||'',status:p.status||'Pendente',observacoes:p.observacoes||'',prioridade:p.prioridade||'Normal',responsavel:p.responsavel||'',prazo:p.prazo||'',encaminhamento:p.encaminhamento||'',retorno:p.retorno||'',secretaria:p.secretaria||'',anexos:Array.isArray(p.anexos)?p.anexos:[],protocolo:p.protocolo||'',destinoEnvio:p.destinoEnvio||'',dataSaida:p.dataSaida||'',atualizadoEm:p.atualizadoEm||p.criadoEm||new Date().toISOString(),criadoEm:p.criadoEm||new Date().toISOString()}];return ds.map(d=>{if(!valid(d.id))d.id=uuid();if(!d.atualizadoEm)d.atualizadoEm=d.criadoEm||p.atualizadoEm||new Date().toISOString();return d})}
function demandRow(p,x){return{id:x.id,cidadao_id:p.id,descricao:x.demanda||'',tipo:x.tipoDemanda||x.tipo||'Outro',procedimento:x.procedimento||null,status:['Pendente','Em andamento','Concluído'].includes(x.status)?x.status:'Pendente',observacoes:x.observacoes||null,prioridade:['Baixa','Normal','Alta','Urgente'].includes(x.prioridade)?x.prioridade:'Normal',responsavel:x.responsavel||null,prazo:date(x.prazo),encaminhamento:x.encaminhamento||null,retorno:x.retorno||null,secretaria:x.secretaria||null,anexos:Array.isArray(x.anexos)?x.anexos:[],protocolo:x.protocolo||null,destino_envio:x.destinoEnvio||null,data_saida:date(x.dataSaida),atualizado_em:x.atualizadoEm||p.atualizadoEm||new Date().toISOString()}}
function remoteProcedimento(x){return{id:x.id,demandaId:x.demanda_id||'',tipo:x.tipo||'Exame',procedimento:x.procedimento||'',local:x.local||'',data:x.data||'',horario:x.horario||'',status:x.status||'Agendado',observacoes:x.observacoes||'',criadoEm:x.criado_em||'',atualizadoEm:x.atualizado_em||''}}\nfunction remotePerson(c,by,pr){const ox=limparOrigem(c.cidade_origem||'');const arr=(by[c.id]||[]).map(x=>({id:x.id,demanda:x.descricao||'',tipoDemanda:x.tipo||'Outro',tipo:x.tipo||'Outro',procedimento:x.procedimento||'',status:x.status||'Pendente',observacoes:x.observacoes||'',prioridade:x.prioridade||'Normal',responsavel:x.responsavel||'',prazo:x.prazo||'',encaminhamento:x.encaminhamento||'',retorno:x.retorno||'',secretaria:x.secretaria||'',protocolo:x.protocolo||'',destinoEnvio:x.destino_envio||'',dataSaida:x.data_saida||'',anexos:Array.isArray(x.anexos)?x.anexos:[],criadoEm:x.criado_em||'',atualizadoEm:x.atualizado_em||''}));const procedimentos=(pr[c.id]||[]).map(remoteProcedimento);return normal({id:c.id,nome:c.nome||'',mae:c.nome_mae||'',nascimento:c.data_nascimento||'',cpf:c.cpf||'',sus:c.cartao_sus||'',telefone:c.telefone||'',bairro:c.bairro||'',endereco:c.endereco||'',cep:c.cep||'',cidadeOrigem:ox.city,estadoOrigem:ox.state,cidadeNascimento:ox.city,estadoNascimento:ox.state,origemNascimento:ox.city&&ox.state?ox.city+' / '+ox.state:ox.city||ox.state||'',apelido:c.apelido||'',pontoReferencia:c.ponto_referencia||'',nacionalidade:c.nacionalidade||'',racaCor:c.raca_cor||'',observacoes:c.observacoes||'',criadoEm:c.criado_em||'',atualizadoEm:c.atualizado_em||'',demandas:arr,procedimentosRealizados:procedimentos})}
async function downloadRemote(){const[cs,ds,ag,prs]=await Promise.all([req('/rest/v1/cidadaos?select=*&order=criado_em.desc'),req('/rest/v1/demandas?select=*&order=criado_em.asc'),req('/rest/v1/agenda?select=*'),req('/rest/v1/procedimentos_realizados?select=*')]);const by={},pr={};(ds||[]).forEach(x=>(by[x.cidadao_id]||(by[x.cidadao_id]=[])).push(x));(prs||[]).forEach(x=>(pr[x.cidadao_id]||(pr[x.cidadao_id]=[])).push(x));return{people:(cs||[]).map(c=>remotePerson(c,by,pr)),agenda:ag||[]}}
async function uploadLocal(d){d.people.forEach(normal);await upsert('cidadaos',d.people.map(personRow));const ds=[];d.people.forEach(p=>demandList(p).forEach(x=>ds.push(demandRow(p,x))));if(ds.length)await upsert('demandas',ds);const prs=[];d.people.forEach(p=>(Array.isArray(p.procedimentosRealizados)?p.procedimentosRealizados:[]).forEach(x=>prs.push({id:x.id||uuid(),cidadao_id:p.id,demanda_id:valid(x.demandaId)?x.demandaId:null,tipo:x.tipo||'Exame',procedimento:x.procedimento||null,local:x.local||null,data:date(x.data),horario:x.horario||null,status:['Agendado','Realizado','Cancelado','Pendente'].includes(x.status)?x.status:'Agendado',observacoes:x.observacoes||null,atualizado_em:x.atualizadoEm||p.atualizadoEm||new Date().toISOString()})));if(prs.length)await upsert('procedimentos_realizados',prs);if(d.agenda.length)await upsert('agenda',d.agenda.map(a=>({id:valid(a.id)?a.id:uuid(),assunto:a.assunto||'Compromisso',data:date(a.data),hora:a.hora||null,tipo:a.tipo||'Outro',status:a.status||'Pendente',observacoes:a.observacoes||null,atualizado_em:a.atualizadoEm||new Date().toISOString()})))}
function status(msg,kind){window.__gabineteSyncStatus={message:msg,kind,at:new Date().toISOString()};window.dispatchEvent(new CustomEvent('gabinete-sync-status',{detail:window.__gabineteSyncStatus}));toast(msg)}
async function sincronizar(){if(get.call(localStorage,LOCK)==='1')return null;set.call(localStorage,LOCK,'1');try{status('☁️ Sincronizando dados...','working');await refreshSession();if(!token())throw Error('Sessão não disponível neste aparelho');const local=read();local.people.forEach(normal);const remote=await downloadRemote();const merged={people:mergePeople(local.people,remote.people),agenda:mergeAgenda(local.agenda,remote.agenda)};write(merged);await uploadLocal(merged);const confirm=await downloadRemote();const final={people:mergePeople(merged.people,confirm.people),agenda:mergeAgenda(merged.agenda,confirm.agenda)};write(final);window.render?.();window.renderDemandas?.();window.renderAgenda?.();window.renderBirthdays?.();window.atualizarPainel?.();status('✅ Sincronizado • '+final.people.length+' cidadãos','ok');return{people:final.people.length}}catch(e){console.error('[Gabinete LM] sincronização',e);status('⚠️ '+e.message,'error');return null}finally{remove.call(localStorage,LOCK)}}
function toast(m){let e=document.getElementById('gabineteToast');if(!e){e=document.createElement('div');e.id='gabineteToast';e.style.cssText='position:fixed;left:50%;bottom:20px;z-index:2147483647;transform:translateX(-50%);background:#111827;color:#fff;padding:12px 16px;border-radius:10px;font:14px Arial;max-width:92%;white-space:pre-line'}document.body.appendChild(e);e.textContent=m;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',5000)}
window.GabineteDB=window.GabineteDB||{};window.GabineteDB.sincronizar=sincronizar;window.GabineteDB.atualizarAgora=sincronizar;window.GabineteDB.renovarSessao=refreshSession;
const wake=()=>{clearTimeout(window.__gabineteWakeSync);window.__gabineteWakeSync=setTimeout(()=>sincronizar(),250)};
setTimeout(()=>sincronizar(),1200);setInterval(()=>sincronizar(),30000);
window.addEventListener('online',wake);window.addEventListener('focus',wake);window.addEventListener('pageshow',wake);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')wake()});
})();