/* GABINETE DIGITAL — sincronização Supabase v4
   Mantém a interface local, mas sincroniza TODOS os dados, inclusive múltiplas demandas por cidadão. */
(function(){
'use strict';
const DB='gabineteDigitalDemo',CFG='gabineteSupabaseConfig',SES='gabineteSupabaseSession',LOCK='__gabinete_v4_syncing__';
const rawGet=Storage.prototype.getItem,rawSet=Storage.prototype.setItem,rawRemove=Storage.prototype.removeItem;
let timer=null,boot=true;
const cfg=()=>{try{return JSON.parse(rawGet.call(localStorage,CFG)||'null')}catch(e){return null}};
const ses=()=>{try{return JSON.parse(rawGet.call(localStorage,SES)||'null')}catch(e){return null}};
const saveSes=v=>rawSet.call(localStorage,SES,JSON.stringify(v));
const clearSes=()=>rawRemove.call(localStorage,SES);
const read=()=>{try{const d=JSON.parse(rawGet.call(localStorage,DB)||'{"people":[],"agenda":[]}');d.people=Array.isArray(d.people)?d.people:[];d.agenda=Array.isArray(d.agenda)?d.agenda:[];return d}catch(e){return{people:[],agenda:[]}}};
const write=d=>rawSet.call(localStorage,DB,JSON.stringify(d));
const uid=()=>crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)});
const valid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const date=v=>{v=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:null};
function toast(m){let e=document.getElementById('gabineteToast');if(!e){e=document.createElement('div');e.id='gabineteToast';e.style.cssText='position:fixed;left:50%;bottom:20px;transform:translateX(-50%);z-index:999999;background:#111827;color:#fff;padding:13px 16px;border-radius:10px;font:14px Arial;max-width:92%;box-shadow:0 8px 30px #0006';document.body.appendChild(e)}e.textContent=m;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',4500)}
function baseUrl(){const c=cfg();return c&&c.url?String(c.url).replace(/\/+$/,''):''}
async function request(path,opt={}){const c=cfg(),s=ses();if(!c?.url||!c?.anonKey)throw Error('Supabase não configurado.');const h=Object.assign({apikey:c.anonKey,'Content-Type':'application/json'},opt.headers||{});if(s?.access_token)h.Authorization='Bearer '+s.access_token;let r=await fetch(baseUrl()+path,Object.assign({},opt,{headers:h}));if(r.status===401&&s?.refresh_token){const rr=await fetch(baseUrl()+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(rr.ok){const ns=await rr.json();saveSes(ns);h.Authorization='Bearer '+ns.access_token;r=await fetch(baseUrl()+path,Object.assign({},opt,{headers:h}))}else clearSes()}if(!r.ok){const t=await r.text();let msg=t;try{const j=JSON.parse(t);msg=j.message||j.error_description||j.details||j.hint||t}catch(e){}throw Error('HTTP '+r.status+': '+msg)}if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function login(email,password){const c=cfg();const r=await fetch(baseUrl()+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:email.trim(),password})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error_description||j.msg||j.message||'E-mail ou senha inválidos.');saveSes(j);return j}
function panel(){if(document.getElementById('gabineteLoginV4'))return;const e=document.createElement('div');e.id='gabineteLoginV4';e.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.78);z-index:999998;display:flex;align-items:center;justify-content:center;padding:18px;font-family:Arial';e.innerHTML='<div style="width:min(480px,100%);background:#171717;color:#fff;border-radius:18px;padding:22px;box-shadow:0 20px 60px #0009"><h2 style="margin:0 0 8px">Gabinete Digital</h2><p id="sbv4msg" style="color:#ccc">Entre para sincronizar os dados com a nuvem.</p><label>E-mail</label><input id="sbv4email" type="email" autocomplete="username" style="width:100%;box-sizing:border-box;margin:6px 0 12px;padding:12px;border-radius:10px;border:1px solid #444;background:#222;color:#fff"><label>Senha</label><input id="sbv4pass" type="password" autocomplete="current-password" style="width:100%;box-sizing:border-box;margin:6px 0 12px;padding:12px;border-radius:10px;border:1px solid #444;background:#222;color:#fff"><button id="sbv4go" style="width:100%;padding:13px;border:0;border-radius:10px;background:#22c55e;font-weight:700;font-size:16px">Entrar e sincronizar</button><button id="sbv4local" style="width:100%;margin-top:9px;padding:11px;border:1px solid #555;border-radius:10px;background:#222;color:#fff">Continuar somente neste aparelho</button></div>';document.body.appendChild(e);e.querySelector('#sbv4go').onclick=async()=>{const msg=e.querySelector('#sbv4msg');msg.textContent='Conectando...';try{await login(e.querySelector('#sbv4email').value,e.querySelector('#sbv4pass').value);e.remove();await bootSync()}catch(x){msg.textContent=x.message||String(x)}};e.querySelector('#sbv4local').onclick=()=>e.remove()}
function normalizePerson(p){if(!valid(p.id))p.id=uid();if(!Array.isArray(p.demandas))p.demandas=[];if(p.demanda&&!p.demandas.length)p.demandas.push({id:valid(p.demandaId)?p.demandaId:uid(),demanda:p.demanda,tipoDemanda:p.tipoDemanda||p.tipo||'Outro',procedimento:p.procedimento||'',status:p.status||'Pendente',observacoes:p.observacoes||'',criadoEm:p.criadoEm||new Date().toISOString()});p.demandas=p.demandas.map(d=>{if(!valid(d.id))d.id=uid();d.status=['Pendente','Em andamento','Concluído'].includes(d.status)?d.status:'Pendente';return d});return p}
async function remote(){const [cs,ds,ag]=await Promise.all([request('/rest/v1/cidadaos?select=*&order=criado_em.desc'),request('/rest/v1/demandas?select=*&order=criado_em.asc'),request('/rest/v1/agenda?select=*&order=data.asc,hora.asc')]);const by={};(ds||[]).forEach(d=>(by[d.cidadao_id]||(by[d.cidadao_id]=[])).push(d));return{people:(cs||[]).map(c=>{const arr=(by[c.id]||[]).map(d=>({id:d.id,demanda:d.descricao||'',tipoDemanda:d.tipo||'Outro',tipo:d.tipo||'Outro',procedimento:d.procedimento||'',status:d.status||'Pendente',observacoes:d.observacoes||'',criadoEm:d.criado_em||''}));const d=arr[arr.length-1]||null;return normalizePerson({id:c.id,nome:c.nome||'',mae:c.nome_mae||'',nascimento:c.data_nascimento||'',cpf:c.cpf||'',sus:c.cartao_sus||'',telefone:c.telefone||'',bairro:c.bairro||'',endereco:c.endereco||'',observacoes:c.observacoes||'',demandas:arr,demanda:d?.demanda||'',tipoDemanda:d?.tipoDemanda||'',tipo:d?.tipo||'',procedimento:d?.procedimento||'',status:d?.status||'Pendente',demandaId:d?.id||null,criadoEm:c.criado_em||''})}),agenda:(ag||[]).map(a=>({id:a.id,assunto:a.assunto||'',data:a.data||'',hora:a.hora?String(a.hora).slice(0,5):'',tipo:a.tipo||'Outro',status:a.status||'Pendente',observacoes:a.observacoes||''}))}}
async function upsert(table,rows){if(rows.length)await request('/rest/v1/'+table+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
async function sync(){if(rawGet.call(localStorage,LOCK)==='1')return;if(!ses()?.access_token)return;rawSet.call(localStorage,LOCK,'1');try{const d=read();d.people.forEach(normalizePerson);const people=d.people.map(p=>({id:p.id,nome:p.nome||'',nome_mae:p.mae||null,data_nascimento:date(p.nascimento),cpf:p.cpf||null,cartao_sus:p.sus||null,telefone:p.telefone||null,bairro:p.bairro||null,endereco:p.endereco||null,observacoes:p.observacoes||null}));const demandas=[];d.people.forEach(p=>p.demandas.forEach(x=>demandas.push({id:x.id,cidadao_id:p.id,descricao:x.demanda||'',tipo:x.tipoDemanda||x.tipo||'Outro',procedimento:x.procedimento||null,status:['Pendente','Em andamento','Concluído'].includes(x.status)?x.status:'Pendente',observacoes:x.observacoes||null})));const agenda=d.agenda.map(a=>({id:valid(a.id)?a.id:(a.id=uid()),assunto:a.assunto||'Compromisso',data:date(a.data),hora:a.hora||null,tipo:a.tipo||'Outro',status:['Pendente','Concluído'].includes(a.status)?a.status:'Pendente',observacoes:a.observacoes||null}));write(d);await upsert('cidadaos',people);await upsert('demandas',demandas);await upsert('agenda',agenda);toast('✓ Sincronizado com o Supabase')}catch(e){console.error(e);toast('⚠️ Sincronização falhou: '+(e.message||e))}finally{rawRemove.call(localStorage,LOCK)}}
async function bootSync(){try{if(!ses()?.access_token){panel();return}const r=await remote();if(r.people.length||r.agenda.length){write(r);if(window.render)window.render();if(window.renderDemandas)window.renderDemandas();if(window.renderAgenda)window.renderAgenda();if(window.renderBirthdays)window.renderBirthdays();if(window.atualizarPainel)window.atualizarPainel()}else if(read().people.length||read().agenda.length){await sync()}boot=false;toast('✓ Dados sincronizados com o Supabase')}catch(e){boot=false;toast('⚠️ Não foi possível carregar o Supabase: '+(e.message||e))}}
const oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){oldSet.call(this,k,v);if(this===localStorage&&k===DB&&!boot&&rawGet.call(localStorage,LOCK)!=='1'){clearTimeout(timer);timer=setTimeout(sync,700)}};
window.GabineteDB=window.GabineteDB||{};window.GabineteDB.sincronizar=sync;window.GabineteDB.v4=true;
document.addEventListener('DOMContentLoaded',()=>setTimeout(bootSync,500),{once:true});
})();
