/* GABINETE DIGITAL — sincronização Supabase v6.3
   Sessão + conflitos: preserva timestamps reais e prefere a versão mais recente. */
(function(){'use strict';
const DB='gabineteDigitalDemo',CFG='gabineteSupabaseConfig',SES='gabineteSupabaseSession',AT='gabineteAccessToken',LOCK='__gabinete_v6_syncing__';
const rawGet=Storage.prototype.getItem,rawSet=Storage.prototype.setItem,rawRemove=Storage.prototype.removeItem;
let timer=null,boot=true,refreshing=null;
const cfg=()=>{try{return JSON.parse(rawGet.call(localStorage,CFG)||'null')}catch(e){return null}};
const ses=()=>{try{return JSON.parse(rawGet.call(localStorage,SES)||'null')}catch(e){return null}};
const token=()=>rawGet.call(localStorage,AT)||ses()?.access_token||'';
const read=()=>{try{const d=JSON.parse(rawGet.call(localStorage,DB)||'{"people":[],"agenda":[]}');d.people=Array.isArray(d.people)?d.people:[];d.agenda=Array.isArray(d.agenda)?d.agenda:[];return d}catch(e){return{people:[],agenda:[]}}};
const write=d=>rawSet.call(localStorage,DB,JSON.stringify(d));
const uid=()=>crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)});
const valid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const date=v=>{v=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:null};
const ts=v=>{const n=Date.parse(v||'');return Number.isFinite(n)?n:0};
function toast(m){let e=document.getElementById('gabineteToast');if(!e){e=document.createElement('div');e.id='gabineteToast';e.style.cssText='position:fixed;left:50%;bottom:20px;transform:translateX(-50%);z-index:2147483647;background:#111827;color:#fff;padding:13px 16px;border-radius:10px;font:14px Arial;max-width:92%;box-shadow:0 8px 30px #0006';document.body.appendChild(e)}e.textContent=m;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',5000)}
function base(){const c=cfg();return c?.url?String(c.url).replace(/\/+$/,''):''}
async function refreshSession(){if(refreshing)return refreshing;const c=cfg(),s=ses(),rt=s?.refresh_token;if(!c?.url||!c?.anonKey||!rt)throw Error('Sessão expirada. Entre novamente.');refreshing=(async()=>{const r=await fetch(base()+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw Error('Sessão expirada. Entre novamente.');const ns=Object.assign({},s,j);rawSet.call(localStorage,SES,JSON.stringify(ns));rawSet.call(localStorage,AT,j.access_token);return j.access_token})().finally(()=>{refreshing=null});return refreshing}
async function req(path,opt={},retry=true){const c=cfg(),t=token();if(!c?.url||!c?.anonKey)throw Error('Supabase não configurado.');const h=Object.assign({apikey:c.anonKey,'Content-Type':'application/json'},opt.headers||{});if(t)h.Authorization='Bearer '+t;let r=await fetch(base()+path,Object.assign({},opt,{headers:h}));if(r.status===401&&retry){try{await refreshSession();return req(path,opt,false)}catch(e){throw e}}if(!r.ok){const txt=await r.text();let j={};try{j=JSON.parse(txt)}catch(e){}throw Error('HTTP '+r.status+': '+(j.message||j.details||j.hint||j.error_description||txt))}if(r.status===204)return null;const txt=await r.text();return txt?JSON.parse(txt):null}
function normalizePerson(p){if(!valid(p.id))p.id=uid();if(!Array.isArray(p.demandas))p.demandas=[];if(p.demanda&&!p.demandas.length)p.demandas.push({id:valid(p.demandaId)?p.demandaId:uid(),demanda:p.demanda,tipoDemanda:p.tipoDemanda||p.tipo||'Outro',procedimento:p.procedimento||'',status:p.status||'Pendente',observacoes:p.observacoes||'',prioridade:p.prioridade||'Normal',responsavel:p.responsavel||'',prazo:p.prazo||'',encaminhamento:p.encaminhamento||'',retorno:p.retorno||'',protocolo:p.protocolo||'',secretaria:p.secretaria||'',anexos:Array.isArray(p.anexos)?p.anexos:[],dataAbertura:p.dataAbertura||'',atualizadoEm:p.atualizadoEm||p.criadoEm||new Date().toISOString(),criadoEm:p.criadoEm||new Date().toISOString()});p.demandas=p.demandas.map(d=>{if(!valid(d.id))d.id=uid();d.status=['Pendente','Em andamento','Concluído'].includes(d.status)?d.status:'Pendente';d.prioridade=['Baixa','Normal','Alta','Urgente'].includes(d.prioridade)?d.prioridade:'Normal';if(!Array.isArray(d.anexos))d.anexos=[];d.atualizadoEm=d.atualizadoEm||d.criadoEm||p.atualizadoEm||new Date().toISOString();return d});return p}
function merge(a,b){const out={people:[],agenda:[]},bp=new Map((b.people||[]).map(p=>[String(p.id),p]));for(const lp0 of(a.people||[])){const lp=normalizePerson(lp0),rp0=bp.get(String(lp.id));if(!rp0){out.people.push(lp);continue}const rp=normalizePerson(rp0);const localNewer=ts(lp.atualizadoEm||lp.criadoEm)>=ts(rp.atualizadoEm||rp.criadoEm);const baseP=localNewer?lp:rp,otherP=localNewer?rp:lp;const dm=new Map((rp.demandas||[]).map(d=>[String(d.id),d]));for(const d of(lp.demandas||[])){const old=dm.get(String(d.id));if(!old||ts(d.atualizadoEm||d.criadoEm)>=ts(old.atualizadoEm||old.criadoEm))dm.set(String(d.id),d)}for(const d of(otherP.demandas||[])){const old=dm.get(String(d.id));if(!old||ts(d.atualizadoEm||d.criadoEm)>=ts(old.atualizadoEm||old.criadoEm))dm.set(String(d.id),d)}out.people.push(Object.assign({},otherP,baseP,{demandas:[...dm.values()]}));bp.delete(String(lp.id))}for(const p of bp.values())out.people.push(p);
const aa=new Map((b.agenda||[]).map(x=>[String(x.id),x]));for(const x of(a.agenda||[])){const old=aa.get(String(x.id));if(!old||ts(x.atualizadoEm||x.criadoEm)>=ts(old.atualizadoEm||old.criadoEm))aa.set(String(x.id),x)}out.agenda=[...aa.values()];return out}
async function sync(){if(rawGet.call(localStorage,LOCK)==='1'||!token())return;rawSet.call(localStorage,LOCK,'1');try{const d=read();d.people.forEach(normalizePerson);const people=d.people.map(p=>({id:p.id,nome:p.nome||'',nome_mae:p.mae||null,data_nascimento:date(p.nascimento),cpf:p.cpf||null,cartao_sus:p.sus||null,telefone:p.telefone||null,bairro:p.bairro||null,endereco:p.endereco||null,observacoes:p.observacoes||null,atualizado_em:p.atualizadoEm||p.criadoEm||null}));await upsert('cidadaos',people);const ids=people.map(p=>p.id).filter(valid);let cloudIds=new Set();if(ids.length){const q=ids.join(',');const rows=await req('/rest/v1/cidadaos?select=id&id=in.('+encodeURIComponent(q)+')');cloudIds=new Set((rows||[]).map(x=>String(x.id)))}const demandas=[];d.people.forEach(p=>{if(!cloudIds.has(String(p.id)))return;(p.demandas||[]).forEach(x=>{const row={id:x.id,cidadao_id:p.id,descricao:x.demanda||'',tipo:x.tipoDemanda||x.tipo||'Outro',procedimento:x.procedimento||null,status:['Pendente','Em andamento','Concluído'].includes(x.status)?x.status:'Pendente',observacoes:x.observacoes||null,prioridade:['Baixa','Normal','Alta','Urgente'].includes(x.prioridade)?x.prioridade:'Normal',responsavel:x.responsavel||null,prazo:date(x.prazo),encaminhamento:x.encaminhamento||null,retorno:x.retorno||null,secretaria:x.secretaria||null,anexos:Array.isArray(x.anexos)?x.anexos:[],atualizado_em:x.atualizadoEm||x.criadoEm||null,concluido_em:x.concluidoEm||null,protocolo:x.protocolo||null};demandas.push(row)})});if(demandas.length)await upsert('demandas',demandas);const agenda=d.agenda.map(a=>({id:valid(a.id)?a.id:(a.id=uid()),assunto:a.assunto||'Compromisso',data:date(a.data),hora:a.hora||null,tipo:a.tipo||'Outro',status:['Pendente','Concluído'].includes(a.status)?a.status:'Pendente',observacoes:a.observacoes||null,atualizado_em:a.atualizadoEm||a.criadoEm||null}));write(d);if(agenda.length)await upsert('agenda',agenda);toast('✓ Sincronizado com o Supabase')}catch(e){console.error(e);toast('⚠️ Sincronização falhou: '+(e.message||e))}finally{rawRemove.call(localStorage,LOCK)}}
async function upsert(table,rows){if(!rows.length)return;await req('/rest/v1/'+table+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
async function remote(){const[cs,ds,ag]=await Promise.all([req('/rest/v1/cidadaos?select=*&order=criado_em.desc'),req('/rest/v1/demandas?select=*&order=criado_em.asc'),req('/rest/v1/agenda?select=*&order=data.asc,hora.asc')]);const by={};(ds||[]).forEach(d=>(by[d.cidadao_id]||(by[d.cidadao_id]=[])).push(d));return{people:(cs||[]).map(c=>{const arr=(by[c.id]||[]).map(d=>({id:d.id,demanda:d.descricao||'',tipoDemanda:d.tipo||'Outro',tipo:d.tipo||'Outro',procedimento:d.procedimento||'',status:d.status||'Pendente',observacoes:d.observacoes||'',prioridade:d.prioridade||'Normal',responsavel:d.responsavel||'',prazo:d.prazo||'',encaminhamento:d.encaminhamento||'',retorno:d.retorno||'',protocolo:d.protocolo||'',secretaria:d.secretaria||'',anexos:Array.isArray(d.anexos)?d.anexos:[],dataAbertura:d.data_abertura||'',atualizadoEm:d.atualizado_em||d.criado_em||'',concluidoEm:d.concluido_em||'',criadoEm:d.criado_em||''}));const last=arr[arr.length-1]||{};return normalizePerson({id:c.id,nome:c.nome||'',mae:c.nome_mae||'',nascimento:c.data_nascimento||'',cpf:c.cpf||'',sus:c.cartao_sus||'',telefone:c.telefone||'',bairro:c.bairro||'',endereco:c.endereco||'',observacoes:c.observacoes||'',demandas:arr,demanda:last.demanda||'',tipoDemanda:last.tipoDemanda||'',tipo:last.tipo||'',procedimento:last.procedimento||'',status:last.status||'Pendente',demandaId:last.id||null,criadoEm:c.criado_em||'',atualizadoEm:c.atualizado_em||c.criado_em||''})}),agenda:(ag||[]).map(a=>({id:a.id,assunto:a.assunto||'',data:a.data||'',hora:a.hora?String(a.hora).slice(0,5):'',tipo:a.tipo||'Outro',status:a.status||'Pendente',observacoes:a.observacoes||'',atualizadoEm:a.atualizado_em||a.criado_em||''}))}}
async function bootSync(){try{if(!token()){boot=false;return}const r=await remote();const local=read();const merged=merge(local,r);write(merged);if(window.render)window.render();if(window.renderDemandas)window.renderDemandas();if(window.renderAgenda)window.renderAgenda();if(window.renderBirthdays)window.renderBirthdays();if(window.atualizarPainel)window.atualizarPainel();boot=false;await sync()}catch(e){boot=false;console.error(e);toast('⚠️ Não foi possível sincronizar: '+(e.message||e))}}
const oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){oldSet.call(this,k,v);if(this===localStorage&&k===DB&&!boot&&rawGet.call(localStorage,LOCK)!=='1'){clearTimeout(timer);timer=setTimeout(sync,700)}};
window.GabineteDB=window.GabineteDB||{};window.GabineteDB.sincronizar=sync;window.GabineteDB.v6=true;document.addEventListener('DOMContentLoaded',()=>setTimeout(bootSync,500),{once:true});
})();