/* GABINETE DIGITAL — BANCO CENTRAL v12
   Supabase como fonte central + atualização resiliente.
   Corrige filtro PostgREST do envio de IDs e normaliza cidade/estado.
   Não apaga dados locais.
*/
(function(){'use strict';
const DB='gabineteDigitalDemo',CFG='gabineteSupabaseConfig',SES='gabineteSupabaseSession',AT='gabineteAccessToken',LOCK='__gabinete_v10_syncing__';
const get=Storage.prototype.getItem,set=Storage.prototype.setItem,remove=Storage.prototype.removeItem;
const states=['Pará','Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Paraná','Paraíba','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins'];
const isState=v=>states.some(s=>s.toLowerCase()===String(v||'').trim().toLowerCase());
const norm=v=>String(v??'').trim().replace(/\s+/g,' ');
const read=()=>{try{const d=JSON.parse(get.call(localStorage,DB)||'{"people":[],"agenda":[]}');d.people=Array.isArray(d.people)?d.people:[];d.agenda=Array.isArray(d.agenda)?d.agenda:[];return d}catch(e){return{people:[],agenda:[]}}};
const write=d=>set.call(localStorage,DB,JSON.stringify(d));
const cfg=()=>{try{return JSON.parse(get.call(localStorage,CFG)||'null')}catch(e){return null}};
const session=()=>{try{return JSON.parse(get.call(localStorage,SES)||'null')}catch(e){return null}};
const token=()=>get.call(localStorage,AT)||session()?.access_token||'';
const base=()=>{const c=cfg();return c?.url?String(c.url).replace(/\/+$/,''):''};
const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const valid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const date=v=>{const s=norm(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);return m?m[3]+'-'+m[2]+'-'+m[1]:null};
function limparOrigem(v){let s=norm(v);if(!s)return{city:'',state:''};const parts=s.split(/\s*(?:\/|-|—|,)\s*/).filter(Boolean);let state='';let cityParts=[];parts.forEach(part=>{const st=states.find(x=>x.toLowerCase()===part.toLowerCase());if(st)state=st;else cityParts.push(part)});if(state)return{city:norm(cityParts.join(' / ')),state};if(isState(s))return{city:'',state:states.find(x=>x.toLowerCase()===s.toLowerCase())||s};return{city:s,state:''}}
function origemCampos(p){let city=norm(p?.cidadeNascimento||p?.cidadeOrigem),state=norm(p?.estadoNascimento||p?.estadoOrigem);if(isState(city)){if(!state)state=city;city=''}if(!state){const s=norm(p?.origemNascimento),x=limparOrigem(s);if(x.state){if(!city)city=x.city;state=x.state}else if(!city)city=x.city}if(isState(city)){if(!state)state=city;city=''}return{city,state}}
function origem(p){const x=origemCampos(p);return x.city&&x.state?x.city+' / '+x.state:x.city||x.state||null}
function normal(p){if(!valid(p.id))p.id=uuid();if(!Array.isArray(p.demandas))p.demandas=[];p.demandas=p.demandas.map(d=>{if(!valid(d.id))d.id=uuid();d.status=['Pendente','Em andamento','Concluído'].includes(d.status)?d.status:'Pendente';return d});return p}
function merge(local,remote){const r=new Map((remote.people||[]).map(p=>[String(p.id),normal(p)])),out=[];for(const raw of(local.people||[])){const l=normal(raw),q=r.get(String(l.id));if(!q){out.push(l);continue}const lc=origemCampos(l),rc=origemCampos(q),city=lc.city||rc.city,state=lc.state||rc.state,merged=Object.assign({},q,l);merged.cidadeNascimento=city;merged.estadoNascimento=state;merged.cidadeOrigem=city;merged.estadoOrigem=state;merged.origemNascimento=city&&state?city+' / '+state:city||state||'';const dm=new Map((q.demandas||[]).map(d=>[String(d.id),d]));(l.demandas||[]).forEach(d=>dm.set(String(d.id),d));merged.demandas=[...dm.values()];out.push(merged);r.delete(String(l.id))}for(const p of r.values())out.push(p);return{people:out,agenda:remote.agenda||local.agenda||[]}}
async function refreshSession(){const c=cfg(),s=session(),rt=s?.refresh_token;if(!c?.url||!c?.anonKey||!rt)return false;try{const res=await fetch(base()+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt}),cache:'no-store'});if(!res.ok)return false;const j=await res.json();if(!j?.access_token)return false;const ns=Object.assign({},s,j);set.call(localStorage,SES,JSON.stringify(ns));set.call(localStorage,AT,j.access_token);return true}catch(e){console.warn('Renovação de sessão:',e);return false}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function req(path,opt={},tentativa=true,retries=2){const c=cfg();if(!c?.url||!c?.anonKey)throw Error('Supabase não configurado');let t=token();const h=Object.assign({apikey:c.anonKey,'Content-Type':'application/json'},opt.headers||{});if(t)h.Authorization='Bearer '+t;let res;try{res=await fetch(base()+path,Object.assign({},opt,{headers:h,cache:'no-store'}))}catch(e){if(retries>0){await sleep(500);return req(path,opt,tentativa,retries-1)}throw Error('Falha de conexão com o Supabase')}if(res.status===401&&tentativa&&await refreshSession())return req(path,opt,false,retries);if(!res.ok){const txt=await res.text();const transient=[408,425,429,500,502,503,504].includes(res.status);if(transient&&retries>0){await sleep(600);return req(path,opt,tentativa,retries-1)}throw Error('HTTP '+res.status+' '+txt)}const txt=await res.text();return txt?JSON.parse(txt):null}
async function upsert(table,rows){if(rows.length)await req('/rest/v1/'+table+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
function parseCloudOrigin(v){return limparOrigem(v)}
async function sync(){if(get.call(localStorage,LOCK)==='1'||!token())return;set.call(localStorage,LOCK,'1');try{const d=read();d.people.forEach(normal);const ids=d.people.map(p=>p.id).filter(valid);let cloud={};if(ids.length){const rows=await req('/rest/v1/cidadaos?select=id,cidade_origem&id=in.('+encodeURIComponent(ids.join(','))+')');(rows||[]).forEach(x=>cloud[String(x.id)]=x.cidade_origem||'')}
const people=d.people.map(p=>{const local=origemCampos(p),co=parseCloudOrigin(cloud[String(p.id)]||'');let value;if(local.city&&local.state)value=local.city+' / '+local.state;else if(local.city)value=local.city;else if(co.city&&co.state)value=co.city+' / '+co.state;else if(co.city)value=co.city;else if(local.state)value=local.state;else value=co.state||null;return{id:p.id,nome:p.nome||'',nome_mae:p.mae||null,data_nascimento:date(p.nascimento),cpf:p.cpf||null,cartao_sus:p.sus||null,telefone:p.telefone||null,bairro:p.bairro||null,endereco:p.endereco||null,cep:p.cep||null,cidade_origem:value,nacionalidade:p.nacionalidade||null,raca_cor:p.racaCor||null,observacoes:p.observacoes||null,atualizado_em:new Date().toISOString()}});await upsert('cidadaos',people);
const ds=[];d.people.forEach(p=>(p.demandas||[]).forEach(x=>ds.push({id:x.id,cidadao_id:p.id,descricao:x.demanda||'',tipo:x.tipoDemanda||x.tipo||'Outro',procedimento:x.procedimento||null,status:x.status||'Pendente',observacoes:x.observacoes||null,prioridade:x.prioridade||'Normal',responsavel:x.responsavel||null,prazo:date(x.prazo),encaminhamento:x.encaminhamento||null,retorno:x.retorno||null,secretaria:x.secretaria||null,anexos:Array.isArray(x.anexos)?x.anexos:[],protocolo:x.protocolo||null,destino_envio:x.destinoEnvio||null,data_saida:date(x.dataSaida)})));if(ds.length)await upsert('demandas',ds);if(d.agenda.length)await upsert('agenda',d.agenda.map(a=>({id:valid(a.id)?a.id:uuid(),assunto:a.assunto||'Compromisso',data:date(a.data),hora:a.hora||null,tipo:a.tipo||'Outro',status:a.status||'Pendente',observacoes:a.observacoes||null})));}catch(e){console.error(e);toast('⚠️ Sincronização: '+e.message)}finally{remove.call(localStorage,LOCK)}}
async function pull(){if(get.call(localStorage,LOCK)==='1'||!token())return;set.call(localStorage,LOCK,'1');try{const[cs,ds,ag]=await Promise.all([req('/rest/v1/cidadaos?select=*&order=criado_em.desc'),req('/rest/v1/demandas?select=*&order=criado_em.asc'),req('/rest/v1/agenda?select=*&order=data.asc,hora.asc')]);const by={};(ds||[]).forEach(x=>(by[x.cidadao_id]||(by[x.cidadao_id]=[])).push(x));const remote={people:(cs||[]).map(c=>{const ox=parseCloudOrigin(c.cidade_origem||'');const arr=(by[c.id]||[]).map(x=>({id:x.id,demanda:x.descricao||'',tipoDemanda:x.tipo||'Outro',tipo:x.tipo||'Outro',procedimento:x.procedimento||'',status:x.status||'Pendente',observacoes:x.observacoes||'',prioridade:x.prioridade||'Normal',responsavel:x.responsavel||'',prazo:x.prazo||'',encaminhamento:x.encaminhamento||'',retorno:x.retorno||'',secretaria:x.secretaria||'',protocolo:x.protocolo||'',destinoEnvio:x.destino_envio||'',dataSaida:x.data_saida||'',anexos:Array.isArray(x.anexos)?x.anexos:[],criadoEm:x.criado_em||'',atualizadoEm:x.atualizado_em||''}));return normal({id:c.id,nome:c.nome||'',mae:c.nome_mae||'',nascimento:c.data_nascimento||'',cpf:c.cpf||'',sus:c.cartao_sus||'',telefone:c.telefone||'',bairro:c.bairro||'',endereco:c.endereco||'',cep:c.cep||'',cidadeOrigem:ox.city,estadoOrigem:ox.state,cidadeNascimento:ox.city,estadoNascimento:ox.state,origemNascimento:ox.city&&ox.state?ox.city+' / '+ox.state:ox.city||ox.state||'',demandas:arr,criadoEm:c.criado_em||'',atualizadoEm:c.atualizado_em||''})}),agenda:(ag||[])};const merged=merge(read(),remote);write(merged);window.render?.();window.renderDemandas?.();window.renderAgenda?.();window.renderBirthdays?.();window.atualizarPainel?.()}catch(e){console.error(e);toast('⚠️ Atualização: '+e.message)}finally{remove.call(localStorage,LOCK)}}
function toast(m){let e=document.getElementById('gabineteToast');if(!e){e=document.createElement('div');e.id='gabineteToast';e.style.cssText='position:fixed;left:50%;bottom:20px;z-index:2147483647;transform:translateX(-50%);background:#111827;color:#fff;padding:12px 16px;border-radius:10px;font:14px Arial;max-width:92%'}document.body.appendChild(e);e.textContent=m;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',4000)}
window.GabineteDB={sincronizar:sync,atualizarAgora:pull,renovarSessao:refreshSession};
setTimeout(async()=>{await refreshSession();await pull();await sync()},800);setInterval(async()=>{await refreshSession();await sync();await pull()},8000);
})();