/* Gabinete Digital — autenticação Supabase + login integrado */
(function(){'use strict';
const KEY='gabinetePerfilAtual',USER='gabineteUsuario',SES='gabineteSupabaseSession',AT='gabineteAccessToken';
const perfis={administrador:{nome:'Administrador',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','relatorios','comunicacao','configuracoes']},vereador:{nome:'Vereador(a)',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','relatorios','comunicacao']},assessor:{nome:'Assessor(a)',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','comunicacao']}};
function cfg(){try{return JSON.parse(localStorage.getItem('gabineteSupabaseConfig')||'{}')}catch(e){return{}}}
function estilos(){if(document.getElementById('authStyle'))return;const s=document.createElement('style');s.id='authStyle';s.textContent='#authModal{position:fixed;inset:0;background:#0f172af2;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:18px;font-family:Arial}.authbox{background:#fff;border-radius:20px;padding:26px;width:min(420px,100%);box-sizing:border-box;box-shadow:0 20px 60px #0006}.authbox input{width:100%;box-sizing:border-box;padding:13px;margin:6px 0 12px;border:1px solid #dbe1ea;border-radius:10px}.authbox button{padding:12px 16px;border:0;border-radius:10px;font-weight:700}.auth-primary{background:#4f46e5;color:#fff;width:100%}.auth-error{color:#dc2626;font-size:13px;min-height:18px;margin:8px 0}';document.head.appendChild(s)}
function login(){if(document.getElementById('authModal'))return;estilos();const m=document.createElement('div');m.id='authModal';m.innerHTML='<div class="authbox"><b style="color:#4f46e5">GABINETE DIGITAL</b><h2>Entrar no sistema</h2><p style="color:#64748b">Faça login para acessar o gabinete.</p><label>E-mail</label><input id="authEmail" type="email" autocomplete="username"><label>Senha</label><input id="authPass" type="password" autocomplete="current-password"><div id="authErr" class="auth-error"></div><button id="authBtn" class="auth-primary">Entrar</button></div>';document.body.appendChild(m);m.querySelector('#authBtn').onclick=async()=>{const e=m.querySelector('#authEmail').value.trim(),p=m.querySelector('#authPass').value,b=m.querySelector('#authBtn'),er=m.querySelector('#authErr');if(!e||!p){er.textContent='Informe e-mail e senha.';return}b.disabled=true;b.textContent='Entrando...';er.textContent='';try{const c=cfg();if(!c.url||!c.anonKey)throw Error('Supabase não configurado.');const r=await fetch(String(c.url).replace(/\/+$/,'')+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});const j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||j.message||'E-mail ou senha inválidos.');
localStorage.setItem(SES,JSON.stringify(j));localStorage.setItem(AT,j.access_token||'');localStorage.setItem(USER,JSON.stringify(j.user||{}));
/* O banco-v4 usa SES; depois do login, não manter o parâmetro que força novo login. */
m.remove();const u=new URL(location.href);u.searchParams.delete('login');u.searchParams.set('v','55');history.replaceState({},'',u.href);if(window.GabineteDB&&typeof window.GabineteDB.sincronizar==='function'){try{await window.GabineteDB.sincronizar()}catch(_){}}location.reload();
}catch(x){er.textContent=x.message||String(x)}finally{b.disabled=false;b.textContent='Entrar'}}}
window.logoutGabinete=()=>{localStorage.removeItem(AT);localStorage.removeItem(SES);localStorage.removeItem(USER);localStorage.removeItem(KEY);location.reload()};window.abrirLoginGabinete=login;window.abrirPerfisGabinete=()=>alert('O perfil de acesso é definido pelo administrador.');
function iniciar(){estilos();const force=new URLSearchParams(location.search).get('login')==='1';if(force){localStorage.removeItem(AT);localStorage.removeItem(SES);localStorage.removeItem(USER);localStorage.removeItem(KEY)}if(!localStorage.getItem(AT)||!localStorage.getItem(SES))login()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar);else iniciar();
})();
