/* Gabinete Digital — autenticação Supabase + perfis e permissões */
(function(){'use strict';
const KEY='gabinetePerfilAtual',USER='gabineteUsuario',SES='gabineteSupabaseSession',AT='gabineteAccessToken';
const perfis={administrador:{nome:'Administrador',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','relatorios','comunicacao','configuracoes']},admin:{nome:'Administrador',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','relatorios','comunicacao','configuracoes']},vereador:{nome:'Vereador(a)',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','relatorios','comunicacao']},assessor:{nome:'Assessor(a)',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios','comunicacao']},atendimento:{nome:'Atendimento',permissoes:['painel','pessoas','cadastro','demandas','agenda','aniversarios']}};
function cfg(){try{return JSON.parse(localStorage.getItem('gabineteSupabaseConfig')||'{}')}catch(e){return{}}}
function estilos(){if(document.getElementById('authStyle'))return;const s=document.createElement('style');s.id='authStyle';s.textContent='#authModal{position:fixed;inset:0;background:#0f172af2;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:18px;font-family:Arial}.authbox{background:#fff;border-radius:20px;padding:26px;width:min(420px,100%);box-sizing:border-box;box-shadow:0 20px 60px #0006}.authbox input{width:100%;box-sizing:border-box;padding:13px;margin:6px 0 12px;border:1px solid #dbe1ea;border-radius:10px}.authbox button{padding:12px 16px;border:0;border-radius:10px;font-weight:700}.auth-primary{background:#4f46e5;color:#fff;width:100%}.auth-error{color:#dc2626;font-size:13px;min-height:18px;margin:8px 0}.perfil-logado{position:fixed;right:14px;top:14px;z-index:1000;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:8px 10px;font:12px Arial;box-shadow:0 5px 18px #0001}.perfil-logado strong{font-size:13px}.perfil-sair{margin-left:8px;border:0;border-radius:8px;padding:5px 8px;cursor:pointer}';document.head.appendChild(s)}
async function buscarPerfil(){const c=cfg(),token=localStorage.getItem(AT);if(!c.url||!c.anonKey||!token)return null;let u={};try{u=JSON.parse(localStorage.getItem(USER)||'{}')}catch(e){}const r=await fetch(String(c.url).replace(/\/+$/,'')+'/rest/v1/perfis_usuario?select=id,nome,perfil&id=eq.'+encodeURIComponent(u.id||''),{headers:{apikey:c.anonKey,Authorization:'Bearer '+token}});if(!r.ok)return null;const a=await r.json();return a[0]||null}
function aplicarPerfil(p){const perfil=perfis[p?.perfil]||perfis.assessor;localStorage.setItem(KEY,JSON.stringify(p));document.querySelectorAll('[data-permissao]').forEach(x=>x.style.display=perfil.permissoes.includes(x.dataset.permissao)?'':'none');document.querySelector('.perfil-logado')?.remove();const d=document.createElement('div');d.className='perfil-logado';d.innerHTML='👤 <strong>'+esc(p?.nome||'Usuário')+'</strong><br>'+esc(perfil.nome)+' <button class="perfil-sair">Sair</button>';document.body.appendChild(d);d.querySelector('button').onclick=window.logoutGabinete}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function login(){if(document.getElementById('authModal'))return;estilos();const m=document.createElement('div');m.id='authModal';m.innerHTML='<div class="authbox"><b style="color:#4f46e5">GABINETE DIGITAL</b><h2>Entrar no sistema</h2><p style="color:#64748b">Faça login para acessar o gabinete.</p><label>E-mail</label><input id="authEmail" type="email" autocomplete="username"><label>Senha</label><input id="authPass" type="password" autocomplete="current-password"><div id="authErr" class="auth-error"></div><button id="authBtn" class="auth-primary">Entrar</button></div>';document.body.appendChild(m);const entrar=async()=>{const e=authEmail.value.trim(),p=authPass.value,b=authBtn,er=authErr;if(!e||!p){er.textContent='Informe e-mail e senha.';return}b.disabled=true;b.textContent='Entrando...';er.textContent='';try{const c=cfg();if(!c.url||!c.anonKey)throw Error('Supabase não configurado.');const r=await fetch(String(c.url).replace(/\/+$/,'')+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});const j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||j.message||'E-mail ou senha inválidos.');localStorage.setItem(SES,JSON.stringify(j));localStorage.setItem(AT,j.access_token||'');localStorage.setItem(USER,JSON.stringify(j.user||{}));const prof=await buscarPerfil();if(!prof)throw Error('Usuário autenticado, mas sem perfil liberado pelo administrador.');aplicarPerfil(prof);m.remove();if(window.GabineteDB?.sincronizar){try{await window.GabineteDB.sincronizar()}catch(_){}}}catch(x){er.textContent=x.message||String(x)}finally{b.disabled=false;b.textContent='Entrar'}};m.querySelector('#authBtn').onclick=entrar;m.querySelector('#authPass').onkeydown=e=>e.key==='Enter'&&entrar()}
window.logoutGabinete=()=>{localStorage.removeItem(AT);localStorage.removeItem(SES);localStorage.removeItem(USER);localStorage.removeItem(KEY);location.reload()};window.abrirLoginGabinete=login;window.abrirPerfisGabinete=()=>{const p=JSON.parse(localStorage.getItem(KEY)||'null');alert('Perfil atual: '+(perfis[p?.perfil]?.nome||p?.perfil||'não definido'))};
async function iniciar(){estilos();const force=new URLSearchParams(location.search).get('login')==='1';if(force){localStorage.removeItem(AT);localStorage.removeItem(SES);localStorage.removeItem(USER);localStorage.removeItem(KEY)}if(!localStorage.getItem(AT)||!localStorage.getItem(SES)){login();return}const p=await buscarPerfil();if(p)aplicarPerfil(p);else login()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar);else iniciar();
})();
