/* GABINETE DIGITAL — Protocolo profissional + histórico v2 */
(function(){'use strict';
const DB='gabineteDigitalDemo';
const read=()=>{try{const d=JSON.parse(localStorage.getItem(DB)||'{"people":[],"agenda":[]}');d.people=Array.isArray(d.people)?d.people:[];return d}catch(e){return{people:[],agenda:[]}}};
const save=d=>localStorage.setItem(DB,JSON.stringify(d));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto?.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
function ensure(){const d=read(),all=[];d.people.forEach(p=>(p.demandas||[]).forEach(x=>all.push({p,x})));let changed=false;all.sort((a,b)=>String(a.x.criadoEm||a.p.criadoEm||'').localeCompare(String(b.x.criadoEm||b.p.criadoEm||'')));const year=new Date().getFullYear();let n=1;all.forEach(({p,x})=>{if(!x.protocolo){x.protocolo=`GD-${year}-${String(n).padStart(6,'0')}`;changed=true}n++;if(!x.dataAbertura){x.dataAbertura=x.criadoEm||p.criadoEm||new Date().toISOString();changed=true}if(!Array.isArray(x.historico))x.historico=[];if(!x.historico.length){x.historico.push({id:uid(),data:x.dataAbertura,titulo:'Demanda cadastrada',responsavel:x.responsavel||'',observacao:'Abertura do atendimento e geração do protocolo.'});changed=true}});if(changed)save(d);return d}
function style(){if(document.getElementById('proV2Style'))return;const s=document.createElement('style');s.id='proV2Style';s.textContent=`.pro-v2{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 14px;margin:12px 0;border:1px solid #e2e8f0;border-radius:14px;background:#f8fafc}.pro-v2 strong{font-size:15px;letter-spacing:.3px;color:#3730a3}.pro-v2 small{display:block;color:#64748b;margin-top:3px}.pro-print{border:0;border-radius:9px;padding:8px 10px;font-weight:700;background:#eef2ff;color:#3730a3;cursor:pointer}.timeline-v2{margin-top:8px}.timeline-v2 .item{display:grid;grid-template-columns:12px 1fr;gap:10px;padding:10px 0;border-bottom:1px solid #eef2f7}.timeline-v2 .dot{width:9px;height:9px;border-radius:50%;background:#4f46e5;margin-top:5px}.timeline-v2 small{color:#64748b}.pro-alert{padding:10px 12px;border-radius:10px;background:#fff7ed;margin-top:8px;font-size:13px}@media(max-width:600px){.pro-v2{align-items:flex-start;flex-direction:column}.pro-print{width:100%}}`;document.head.appendChild(s)}
function findFromCard(card){const h=card.querySelector('h3');const pn=[...card.querySelectorAll('p')].find(x=>x.textContent.includes('Pessoa:'));if(!h||!pn)return null;const name=pn.textContent.replace('Pessoa:','').trim(),dem=h.textContent.trim(),d=ensure(),p=d.people.find(x=>x.nome===name);if(!p)return null;const x=(p.demandas||[]).find(z=>z.demanda===dem);return x?{d,p,x}:null}
function printProtocol(r){const x=r.x,p=r.p;const hist=(x.historico||[]).slice().sort((a,b)=>new Date(a.data)-new Date(b.data));const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(x.protocolo)}</title><style>body{font-family:Arial;margin:40px;color:#111827}h1{margin-bottom:4px}.muted{color:#64748b}.box{border:1px solid #ddd;border-radius:12px;padding:16px;margin:14px 0}.linha{margin:8px 0}.linha b{display:inline-block;min-width:130px}.item{border-left:3px solid #4f46e5;padding:8px 0 8px 12px;margin:8px 0}</style></head><body><h1>Gabinete Digital</h1><p class="muted">Comprovante de atendimento</p><div class="box"><h2>${esc(x.protocolo)}</h2><div class="linha"><b>Cidadão:</b>${esc(p.nome)}</div><div class="linha"><b>Demanda:</b>${esc(x.demanda)}</div><div class="linha"><b>Tipo:</b>${esc(x.tipoDemanda||x.tipo||'Outro')}</div><div class="linha"><b>Abertura:</b>${new Date(x.dataAbertura||x.criadoEm||Date.now()).toLocaleString('pt-BR')}</div><div class="linha"><b>Status:</b>${esc(x.status||'Pendente')}</div><div class="linha"><b>Prioridade:</b>${esc(x.prioridade||'Normal')}</div><div class="linha"><b>Responsável:</b>${esc(x.responsavel||'Não informado')}</div><div class="linha"><b>Prazo:</b>${x.prazo?new Date(x.prazo+'T00:00:00').toLocaleDateString('pt-BR'):'Não informado'}</div><div class="linha"><b>Encaminhamento:</b>${esc(x.encaminhamento||'Não informado')}</div><div class="linha"><b>Retorno:</b>${esc(x.retorno||'Não informado')}</div></div><h2>Histórico</h2>${hist.map(h=>`<div class="item"><b>${esc(h.titulo||'Atualização')}</b><br><span class="muted">${new Date(h.data).toLocaleString('pt-BR')}${h.responsavel?' • '+esc(h.responsavel):''}</span>${h.observacao?`<p>${esc(h.observacao)}</p>`:''}</div>`).join('')||'<p>Sem histórico.</p>'}<script>window.onload=()=>window.print()</script></body></html>`;const w=window.open('','_blank');if(w){w.document.write(html);w.document.close()}}
window.imprimirProtocolo=printProtocol;
function decorate(){style();const d=ensure();document.querySelectorAll('#listaDemandas .card').forEach(card=>{if(card.querySelector('.pro-v2'))return;const r=findFromCard(card);if(!r)return;const x=r.x;const el=document.createElement('div');el.className='pro-v2';el.innerHTML=`<div><strong>📄 ${esc(x.protocolo)}</strong><small>Abertura: ${x.dataAbertura?new Date(x.dataAbertura).toLocaleDateString('pt-BR'):'—'} • ${esc(x.prioridade||'Normal')} • ${esc(x.responsavel||'Sem responsável')}</small></div><button class="pro-print" type="button">🖨️ Protocolo</button>`;el.querySelector('button').onclick=()=>printProtocol(r);const h=card.querySelector('h3');h?.insertAdjacentElement('afterend',el)});const modal=document.querySelector('#gestaoDemModal .gd-modal');if(modal&&!modal.querySelector('.pro-v2')){const h=modal.querySelector('h2');const name=modal.querySelector('.gd-head p')?.textContent?.split('•')[0]?.trim();const p=d.people.find(z=>z.nome===name),x=p?.demandas?.find(z=>z.demanda===h?.textContent?.trim());if(x){const el=document.createElement('div');el.className='pro-v2';el.innerHTML=`<div><strong>📄 ${esc(x.protocolo)}</strong><small>Aberto em ${x.dataAbertura?new Date(x.dataAbertura).toLocaleString('pt-BR'):'—'}</small></div><button class="pro-print" type="button">🖨️ Imprimir protocolo</button>`;el.querySelector('button').onclick=()=>printProtocol({p,x});h?.insertAdjacentElement('afterend',el);const hist=modal.querySelector('#gdHistory');if(hist&&!hist.dataset.prov2){hist.dataset.prov2='1';hist.innerHTML=(x.historico||[]).slice().reverse().map(z=>`<div class="gd-history"><i class="gd-dot"></i><div><strong>${esc(z.titulo||'Atualização')}</strong><br><small>${new Date(z.data).toLocaleString('pt-BR')}${z.responsavel?' • '+esc(z.responsavel):''}</small>${z.observacao?`<div>${esc(z.observacao)}</div>`:''}</div></div>`).join('')||'<p>Nenhuma atualização registrada ainda.</p>'}}}}
const oldRender=window.renderDemandas;window.renderDemandas=function(){oldRender?.();setTimeout(decorate,30)};document.addEventListener('DOMContentLoaded',()=>{ensure();setTimeout(decorate,600);setInterval(()=>{ensure();decorate()},2500)});
})();
