/* GABINETE DIGITAL — Ficha 360 do cidadão */
(function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const getDB=()=>{try{return JSON.parse(localStorage.getItem('gabineteDigitalDemo')||'{"people":[]}')}catch(e){return{people:[]}}};
  const formatDate=v=>{if(!v)return 'Não informado';const s=String(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return new Date(s+'T00:00:00').toLocaleDateString('pt-BR');const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('pt-BR')};
  const prazoClass=d=>{if(!d.prazo||d.status==='Concluído')return '';const x=new Date(d.prazo+'T23:59:59'),n=new Date();return x<n?' atrasada':x.toDateString()===n.toDateString()?' vence-hoje':''};
  const prioridade=d=>d.prioridade==='Urgente'?'🔥 Urgente':d.prioridade==='Alta'?'⚠️ Alta':d.prioridade||'Normal';
  window.verFichaCidadao=function(id){
    const p=(getDB().people||[]).find(x=>x.id===id);if(!p)return alert('Cidadão não encontrado.');
    const ds=Array.isArray(p.demandas)?p.demandas:(p.demanda?[{id:'principal',demanda:p.demanda,tipoDemanda:p.tipoDemanda||p.tipo,procedimento:p.procedimento,status:p.status||'Pendente',criadoEm:p.criadoEm,observacoes:p.observacoes,prioridade:p.prioridade,prazo:p.prazo,responsavel:p.responsavel}]:[]);
    let m=document.getElementById('fichaCidadao');if(!m){m=document.createElement('div');m.id='fichaCidadao';m.className='modal-ficha';document.body.appendChild(m)}
    const pend=ds.filter(d=>(d.status||'Pendente')==='Pendente').length,and=ds.filter(d=>d.status==='Em andamento').length,conc=ds.filter(d=>d.status==='Concluído').length;
    const hist=ds.flatMap(d=>Array.isArray(d.historico)?d.historico.map(h=>({...h,demanda:d.demanda})):[]).sort((a,b)=>new Date(b.data||b.criadoEm||0)-new Date(a.data||a.criadoEm||0));
    m.innerHTML='<div class="ficha"><div class="ficha-topo"><div><span class="eyebrow">FICHA 360 DO CIDADÃO</span><h2>'+esc(p.nome||'Sem nome')+'</h2><p class="ficha-meta">Cadastro: '+formatDate(p.criadoEm)+' • '+ds.length+' demanda(s)</p></div><button type="button" class="fechar-ficha">✕</button></div>'+
      '<div class="ficha-resumo"><div><span>Total de demandas</span><strong>'+ds.length+'</strong></div><div><span>Pendentes</span><strong>'+pend+'</strong></div><div><span>Em andamento</span><strong>'+and+'</strong></div><div><span>Concluídas</span><strong>'+conc+'</strong></div></div>'+
      '<div class="ficha-grid"><div><small>CPF</small><strong>'+esc(p.cpf||'Não informado')+'</strong></div><div><small>Telefone / WhatsApp</small><strong>'+esc(p.telefone||'Não informado')+'</strong></div><div><small>Nascimento</small><strong>'+formatDate(p.nascimento)+'</strong></div><div><small>Cartão SUS</small><strong>'+esc(p.sus||'Não informado')+'</strong></div><div><small>Nome da mãe</small><strong>'+esc(p.mae||'Não informado')+'</strong></div><div><small>Bairro / Comunidade</small><strong>'+esc(p.bairro||'Não informado')+'</strong></div><div class="ficha-full"><small>Endereço</small><strong>'+esc(p.endereco||'Não informado')+'</strong></div></div>'+
      '<div class="ficha-secao"><div class="ficha-secao-titulo"><h3>📋 Demandas e protocolos</h3><span>'+ds.length+' registro(s)</span></div>'+(ds.length?ds.map((d,i)=>'<div class="demanda-historico '+prazoClass(d)+'"><div class="demanda-corpo"><strong>#'+(i+1)+' — '+esc(d.demanda||'Demanda')+'</strong><p>'+esc(d.tipoDemanda||d.tipo||'Tipo não informado')+(d.procedimento?' • '+esc(d.procedimento):'')+'</p><div class="demanda-tags"><span class="status '+(d.status==='Concluído'?'concluido':d.status==='Em andamento'?'andamento':'pendente')+'">'+esc(d.status||'Pendente')+'</span><span class="tag-prioridade">'+esc(prioridade(d))+'</span>'+(d.prazo?'<span class="tag-prazo">📅 '+formatDate(d.prazo)+'</span>':'')+'</div>'+(d.protocolo?'<small>📄 Protocolo: <strong>'+esc(d.protocolo)+'</strong></small><br>':'')+(d.responsavel?'<small>👤 Responsável: '+esc(d.responsavel)+'</small><br>':'')+(d.encaminhamento?'<small>📨 Encaminhamento: '+esc(d.encaminhamento)+'</small><br>':'')+(d.retorno?'<small>📲 Retorno: '+esc(d.retorno)+'</small><br>':'')+(d.observacoes?'<small class="demanda-obs">📝 '+esc(d.observacoes)+'</small>':'')+'<small class="demanda-data">Registrada em '+formatDate(d.criadoEm||p.criadoEm)+'</small></div><div class="demanda-botoes">'+(d.id&&d.id!=='principal'?'<button type="button" class="mini-gerenciar" data-did="'+esc(d.id)+'">⚙️ Gerenciar</button>':'')+'<button type="button" class="mini-protocolo" data-did="'+esc(d.id||'principal')+'">🖨️ Protocolo</button></div></div>').join(''):'<div class="card vazio"><p>Nenhuma demanda cadastrada.</p></div>')+'</div>'+
      '<div class="ficha-secao"><div class="ficha-secao-titulo"><h3>📜 Linha do tempo</h3><span>'+hist.length+' registro(s)</span></div>'+(hist.length?'<div class="timeline">'+hist.map(h=>'<div class="timeline-item"><div class="timeline-dot"></div><div><strong>'+esc(h.acao||h.evento||'Atualização')+'</strong><p>'+esc(h.descricao||h.observacao||h.demanda||'')+'</p><small>'+formatDate(h.data||h.criadoEm)+(h.usuario?' • '+esc(h.usuario):'')+'</small></div></div>').join('')+'</div>':'<div class="ficha-observacoes">Nenhuma movimentação histórica registrada ainda.</div>')+'</div>'+
      '<div class="ficha-secao"><h3>📝 Observações gerais</h3><div class="ficha-observacoes">'+esc(p.observacoes||'Nenhuma observação registrada.')+'</div></div>'+
      '<div class="ficha-acoes"><button type="button" id="fEditar">✏️ Editar cadastro</button><button type="button" id="fNova">+ Nova demanda</button>'+(p.telefone?'<button type="button" id="fWhats">📱 WhatsApp</button>':'')+'<button type="button" onclick="window.print()">🖨️ Imprimir ficha</button></div></div>';
    m.querySelector('.fechar-ficha').onclick=()=>m.remove();
    m.querySelector('#fEditar').onclick=()=>{m.remove();window.editarCadastro?.(id)};
    m.querySelector('#fNova').onclick=()=>{m.remove();window.adicionarDemanda?.(id)};
    if(p.telefone)m.querySelector('#fWhats').onclick=()=>window.wa?.(p.telefone,'Olá, '+p.nome+'! Estou entrando em contato pelo Gabinete Digital.');
    m.querySelectorAll('.mini-gerenciar').forEach(b=>b.onclick=()=>{m.remove();window.gerenciarDemanda?.(id,b.dataset.did)});
    m.querySelectorAll('.mini-protocolo').forEach(b=>b.onclick=()=>{const d=ds.find(x=>String(x.id)===String(b.dataset.did));if(window.imprimirProtocolo)window.imprimirProtocolo(p,d);else window.print()});
    m.onclick=e=>{if(e.target===m)m.remove()};
  };
  if(!document.getElementById('ficha360Style')){const css=document.createElement('style');css.id='ficha360Style';css.textContent='.demanda-tags{display:flex;gap:6px;flex-wrap:wrap;margin:7px 0}.tag-prioridade,.tag-prazo{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;background:#f1f5f9;color:#475569;font-size:11px;font-weight:700}.demanda-botoes{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:10px}.demanda-botoes button{border:0;border-radius:9px;padding:8px 10px;font-weight:700;font-size:12px;cursor:pointer}.mini-gerenciar{background:#eef2ff;color:#3730a3}.mini-protocolo{background:#f1f5f9;color:#334155}.demanda-historico.atrasada{border-left:4px solid #dc2626;padding-left:10px}.demanda-historico.vence-hoje{border-left:4px solid #f59e0b;padding-left:10px}.demanda-corpo{min-width:0}@media(max-width:600px){.demanda-botoes button{flex:1}}';document.head.appendChild(css)}
})();